In [11]:
library("ggplot2")
library("tidyr")

In [12]:
df <- read.table(
  "GENDER_EMP_19032023152556091.txt", sep = "\t", header = FALSE,
  comment.char = "#", na.strings = c(""," ", NA),
  stringsAsFactors = FALSE, quote = "", fill = FALSE, skip = 1
)
names(df) <- c("COU", "Country", "IND", "Indicator", "SEX", "Sex",
  "AGE", "Age Group", "TIME", "Time", "Unit Code", "Unit", "PowerCode Code",
  "PowerCode", "Reference Period Code", "Reference Period", "Value", "Flag Codes", "Flags"
)
df

      COU  Country        IND
1     AUS  Australia      EMP6
2     AUS  Australia      EMP6
3     AUS  Australia      EMP6
4     AUS  Australia      EMP6
5     AUS  Australia      EMP6
6     AUS  Australia      EMP6
7     AUT  Austria        EMP6
8     AUT  Austria        EMP6
9     AUT  Austria        EMP6
10    AUT  Austria        EMP6
11    AUT  Austria        EMP6
12    AUT  Austria        EMP6
13    AUT  Austria        EMP6
14    AUT  Austria        EMP6
15    AUT  Austria        EMP6
16    AUT  Austria        EMP6
17    AUT  Austria        EMP6
18    AUT  Austria        EMP6
19    BEL  Belgium        EMP6
20    BEL  Belgium        EMP6
21    BEL  Belgium        EMP6
22    BEL  Belgium        EMP6
23    BEL  Belgium        EMP6
24    BEL  Belgium        EMP6
25    BEL  Belgium        EMP6
26    BEL  Belgium        EMP6
27    BEL  Belgium        EMP6
28    BEL  Belgium        EMP6
29    BEL  Belgium        EMP6
30    BEL  Belgium        EMP6
â‹®     â‹®    â‹®              â‹®
37111 ESP  Spain          EMP9_9
37112 ESP  Spain          EMP9_5
37113 SWE  Sweden         EMP9_1
37114 SWE  Sweden         EMP9_9
37115 SWE  Sweden         EMP9_5
37116 COL  Colombia       EMP9_1
37117 COL  Colombia       EMP9_5
37118 CRI  Costa Rica     EMP9_1
37119 CRI  Costa Rica     EMP9_5
37120 EST  Estonia        EMP9_1
37121 EST  Estonia        EMP9_1
37122 EST  Estonia        EMP9_9
37123 EST  Estonia        EMP9_9
37124 EST  Estonia        EMP9_5
37125 EST  Estonia        EMP9_5
37126 LVA  Latvia         EMP9_1
37127 LVA  Latvia         EMP9_1
37128 LVA  Latvia         EMP9_9
37129 LVA  Latvia         EMP9_9
37130 LVA  Latvia         EMP9_5
37131 LVA  Latvia         EMP9_5
37132 LTU  Lithuania      EMP9_1
37133 LTU  Lithuania      EMP9_1
37134 LTU  Lithuania      EMP9_9
37135 LTU  Lithuania      EMP9_9
37136 LTU  Lithuania      EMP9_5
37137 LTU  Lithuania      EMP9_5
37138 OAVG OECD - Average EMP9_1
37139 OAVG OECD - Average EMP9_9
37140 OAVG OECD - Average EMP9_5
      Indicator
1     Share of employed in involuntary part-time employment, by sex and age group
2     Share of employed in involuntary part-time employment, by sex and age group
3     Share of employed in involuntary part-time employment, by sex and age group
4     Share of employed in involuntary part-time employment, by sex and age group
5     Share of employed in involuntary part-time employment, by sex and age group
6     Share of employed in involuntary part-time employment, by sex and age group
7     Share of employed in involuntary part-time employment, by sex and age group
8     Share of employed in involuntary part-time employment, by sex and age group
9     Share of employed in involuntary part-time employment, by sex and age group
10    Share of employed in involuntary part-time employment, by sex and age group
11    Share of employed in involuntary part-time employment, by sex and age group
12    Share of employed in involuntary part-time employment, by sex and age group
13    Share of employed in involuntary part-time employment, by sex and age group
14    Share of employed in involuntary part-time employment, by sex and age group
15    Share of employed in involuntary part-time employment, by sex and age group
16    Share of employed in involuntary part-time employment, by sex and age group
17    Share of employed in involuntary part-time employment, by sex and age group
18    Share of employed in involuntary part-time employment, by sex and age group
19    Share of employed in involuntary part-time employment, by sex and age group
20    Share of employed in involuntary part-time employment, by sex and age group
21    Share of employed in involuntary part-time employment, by sex and age group
22    Share of employed in involuntary part-time employment, by sex and age group
23    Share of employed in involuntary part-time employment, by sex and age group
24    Share of employed in involuntary part-time employment, by sex and age group
25    Share of employed in involuntary part-time employment, by sex and age group
26    Share of employed in involuntary part-time employment, by sex and age group
27    Share of employed in involuntary part-time employment, by sex and age group
28    Share of employed in involuntary part-time employment, by sex and age group
29    Share of employed in involuntary part-time employment, by sex and age group
30    Share of employed in involuntary part-time employment, by sex and age group
â‹®     â‹®
37111 Gender wage gap at 9th decile (top)
37112 Gender wage gap at median
37113 Gender wage gap at 1st decile (bottom)
37114 Gender wage gap at 9th decile (top)
37115 Gender wage gap at median
37116 Gender wage gap at 1st decile (bottom)
37117 Gender wage gap at median
37118 Gender wage gap at 1st decile (bottom)
37119 Gender wage gap at median
37120 Gender wage gap at 1st decile (bottom)
37121 Gender wage gap at 1st decile (bottom)
37122 Gender wage gap at 9th decile (top)
37123 Gender wage gap at 9th decile (top)
37124 Gender wage gap at median
37125 Gender wage gap at median
37126 Gender wage gap at 1st decile (bottom)
37127 Gender wage gap at 1st decile (bottom)
37128 Gender wage gap at 9th decile (top)
37129 Gender wage gap at 9th decile (top)
37130 Gender wage gap at median
37131 Gender wage gap at median
37132 Gender wage gap at 1st decile (bottom)
37133 Gender wage gap at 1st decile (bottom)
37134 Gender wage gap at 9th decile (top)
37135 Gender wage gap at 9th decile (top)
37136 Gender wage gap at median
37137 Gender wage gap at median
37138 Gender wage gap at 1st decile (bottom)
37139 Gender wage gap at 9th decile (top)
37140 Gender wage gap at median
      SEX         Sex         AGE    Age Group TIME Time Unit Code Unit
1     ALL_PERSONS All persons 55PLUS 55+       2005 2005 PC        Percentage
2     ALL_PERSONS All persons 55PLUS 55+       2010 2010 PC        Percentage
3     MEN         Men         55PLUS 55+       2005 2005 PC        Percentage
4     MEN         Men         55PLUS 55+       2010 2010 PC        Percentage
5     WOMEN       Women       55PLUS 55+       2005 2005 PC        Percentage
6     WOMEN       Women       55PLUS 55+       2010 2010 PC        Percentage
7     ALL_PERSONS All persons 55PLUS 55+       1995 1995 PC        Percentage
8     ALL_PERSONS All persons 55PLUS 55+       2000 2000 PC        Percentage
9     ALL_PERSONS All persons 55PLUS 55+       2005 2005 PC        Percentage
10    ALL_PERSONS All persons 55PLUS 55+       2010 2010 PC        Percentage
11    MEN         Men         55PLUS 55+       1995 1995 PC        Percentage
12    MEN         Men         55PLUS 55+       2000 2000 PC        Percentage
13    MEN         Men         55PLUS 55+       2005 2005 PC        Percentage
14    MEN         Men         55PLUS 55+       2010 2010 PC        Percentage
15    WOMEN       Women       55PLUS 55+       1995 1995 PC        Percentage
16    WOMEN       Women       55PLUS 55+       2000 2000 PC        Percentage
17    WOMEN       Women       55PLUS 55+       2005 2005 PC        Percentage
18    WOMEN       Women       55PLUS 55+       2010 2010 PC        Percentage
19    ALL_PERSONS All persons 55PLUS 55+       1990 1990 PC        Percentage
20    ALL_PERSONS All persons 55PLUS 55+       1995 1995 PC        Percentage
21    ALL_PERSONS All persons 55PLUS 55+       2000 2000 PC        Percentage
22    ALL_PERSONS All persons 55PLUS 55+       2005 2005 PC        Percentage
23    ALL_PERSONS All persons 55PLUS 55+       2010 2010 PC        Percentage
24    MEN         Men         55PLUS 55+       1990 1990 PC        Percentage
25    MEN         Men         55PLUS 55+       1995 1995 PC        Percentage
26    MEN         Men         55PLUS 55+       2000 2000 PC        Percentage
27    MEN         Men         55PLUS 55+       2005 2005 PC        Percentage
28    MEN         Men         55PLUS 55+       2010 2010 PC        Percentage
29    WOMEN       Women       55PLUS 55+       1990 1990 PC        Percentage
30    WOMEN       Women       55PLUS 55+       1995 1995 PC        Percentage
â‹®     â‹®           â‹®           â‹®      â‹®         â‹®    â‹®    â‹®         â‹®
37111 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37112 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37113 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37114 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37115 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37116 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37117 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37118 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37119 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37120 ALL_PERSONS All persons TOTAL  Total     2019 2019 NA        NA
37121 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37122 ALL_PERSONS All persons TOTAL  Total     2019 2019 NA        NA
37123 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37124 ALL_PERSONS All persons TOTAL  Total     2019 2019 NA        NA
37125 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37126 ALL_PERSONS All persons TOTAL  Total     2020 2020 NA        NA
37127 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37128 ALL_PERSONS All persons TOTAL  Total     2020 2020 NA        NA
37129 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37130 ALL_PERSONS All persons TOTAL  Total     2020 2020 NA        NA
37131 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37132 ALL_PERSONS All persons TOTAL  Total     2019 2019 NA        NA
37133 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37134 ALL_PERSONS All persons TOTAL  Total     2019 2019 NA        NA
37135 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37136 ALL_PERSONS All persons TOTAL  Total     2019 2019 NA        NA
37137 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37138 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37139 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
37140 ALL_PERSONS All persons TOTAL  Total     2021 2021 NA        NA
      PowerCode Code PowerCode Reference Period Code Reference Period Value
1     0              Units     NA                    NA               4.5
2     0              Units     NA                    NA               5.0
3     0              Units     NA                    NA               3.6
4     0              Units     NA                    NA               4.2
5     0              Units     NA                    NA               5.9
6     0              Units     NA                    NA               6.2
7     0              Units     NA                    NA               0.9
8     0              Units     NA                    NA               2.3
9     0              Units     NA                    NA               3.1
10    0              Units     NA                    NA               2.3
11    0              Units     NA                    NA               0.1
12    0              Units     NA                    NA               1.9
13    0              Units     NA                    NA               1.7
14    0              Units     NA                    NA               1.2
15    0              Units     NA                    NA               2.6
16    0              Units     NA                    NA               3.1
17    0              Units     NA                    NA               5.4
18    0              Units     NA                    NA               3.9
19    0              Units     NA                    NA               0.9
20    0              Units     NA                    NA               1.0
21    0              Units     NA                    NA               1.8
22    0              Units     NA                    NA               2.1
23    0              Units     NA                    NA               1.5
24    0              Units     NA                    NA               0.1
25    0              Units     NA                    NA               0.5
26    0              Units     NA                    NA               0.5
27    0              Units     NA                    NA               0.9
28    0              Units     NA                    NA               0.8
29    0              Units     NA                    NA               3.4
30    0              Units     NA                    NA               2.2
â‹®     â‹®              â‹®         â‹®                     â‹®                â‹®
37111 0              Units     NA                    NA                9.2
37112 0              Units     NA                    NA                3.7
37113 0              Units     NA                    NA                4.4
37114 0              Units     NA                    NA               14.6
37115 0              Units     NA                    NA                7.2
37116 0              Units     NA                    NA               28.6
37117 0              Units     NA                    NA                3.2
37118 0              Units     NA                    NA               27.5
37119 0              Units     NA                    NA                5.2
37120 0              Units     NA                    NA               14.8
37121 0              Units     NA                    NA                6.7
37122 0              Units     NA                    NA               25.6
37123 0              Units     NA                    NA               28.1
37124 0              Units     NA                    NA               23.2
37125 0              Units     NA                    NA               20.4
37126 0              Units     NA                    NA               17.1
37127 0              Units     NA                    NA               13.0
37128 0              Units     NA                    NA               25.1
37129 0              Units     NA                    NA               29.6
37130 0              Units     NA                    NA               22.7
37131 0              Units     NA                    NA               24.0
37132 0              Units     NA                    NA                8.1
37133 0              Units     NA                    NA               12.2
37134 0              Units     NA                    NA               26.4
37135 0              Units     NA                    NA               16.5
37136 0              Units     NA                    NA               14.1
37137 0              Units     NA                    NA                9.0
37138 0              Units     NA                    NA                9.6
37139 0              Units     NA                    NA               17.1
37140 0              Units     NA                    NA               11.9
      Flag Codes Flags
1     NA         NA
2     NA         NA
3     NA         NA
4     NA         NA
5     NA         NA
6     NA         NA
7     NA         NA
8     NA         NA
9     NA         NA
10    NA         NA
11    NA         NA
12    NA         NA
13    NA         NA
14    NA         NA
15    NA         NA
16    NA         NA
17    NA         NA
18    NA         NA
19    NA         NA
20    NA         NA
21    NA         NA
22    NA         NA
23    NA         NA
24    NA         NA
25    NA         NA
26    NA         NA
27    NA         NA
28    NA         NA
29    NA         NA
30    NA         NA
â‹®     â‹®          â‹®
37111 NA         NA
37112 NA         NA
37113 NA         NA
37114 NA         NA
37115 NA         NA
37116 NA         NA
37117 NA         NA
37118 NA         NA
37119 NA         NA
37120 NA         NA
37121 NA         NA
37122 NA         NA
37123 NA         NA
37124 NA         NA
37125 NA         NA
37126 NA         NA
37127 NA         NA
37128 NA         NA
37129 NA         NA
37130 NA         NA
37131 NA         NA
37132 NA         NA
37133 NA         NA
37134 NA         NA
37135 NA         NA
37136 NA         NA
37137 NA         NA
37138 NA         NA
37139 NA         NA
37140 NA         NA